# Generated by Django 6.0 on 2026-04-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.TextField(),
        ),
    ]
