# Generated by Django 6.0 on 2026-03-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='crn',
            field=models.IntegerField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_name',
            field=models.TextField(max_length=50),
        ),
    ]
