# Generated by Django 6.0 on 2026-04-09 17:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_alter_classroom_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='due_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='crn',
            field=models.IntegerField(blank=True),
        ),
    ]
