# Generated by Django 6.0 on 2026-04-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_exercise_due_date_exercise_updated_task_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='due_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
