# Generated by Django 6.0 on 2026-04-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_alter_exercise_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='total_points',
            new_name='max_points',
        ),
        migrations.AddField(
            model_name='classroom',
            name='max_points',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='score',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
            preserve_default=False,
        ),
    ]
