# Generated by Django 6.0 on 2026-04-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_rename_total_points_task_max_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='earned_points',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
