# Generated by Django 6.0 on 2026-04-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_classroom_earned_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='max_points',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroom',
            name='earned_points',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='earned_points',
            field=models.IntegerField(blank=True),
        ),
    ]
