# Generated by Django 6.0 on 2026-04-13 16:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_exercise_max_points_alter_classroom_earned_points_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ('created',)},
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='submitted',
            new_name='attempted_time',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='task',
        ),
        migrations.AddField(
            model_name='submission',
            name='exercise',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_submission', to='classroom.exercise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='input_flag',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
